### ISSUE TITLE
牛逼作者，不过我有一个问题是Xlstm真的比transformer要好用吗 还是说得观察一段时间

### ISSUE THREAD

**Issue by Majorry** [swjtuer0762/xLSTMTime#2]
RT

**Comment by swjtuer0762** [comment]
建议观察一段时间，我运行过原作者的代码，效果很差



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月8日(周五) 上午10:31
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [swjtuer0762/xLSTMTime] 牛逼作者，不过我有一个问题是Xlstm真的比transformer要好用吗 还是说得观察一段时间 (Issue #2)




 
RT

**Comment by Majorry** [comment]
> 建议观察一段时间，我运行过原作者的代码，效果很差
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年11月8日(周五) 上午10:31 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [swjtuer0762/xLSTMTime] 牛逼作者，不过我有一个问题是Xlstm真的比transformer要好用吗 还是说得观察一段时间 (Issue #2) RT — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

**Comment by Majorry** [comment]
> 建议观察一段时间，我运行过原作者的代码，效果很差
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年11月8日(周五) 上午10:31 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [swjtuer0762/xLSTMTime] 牛逼作者，不过我有一个问题是Xlstm真的比transformer要好用吗 还是说得观察一段时间 (Issue #2) RT — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

确实 我感觉LSTM效果都比X参数量要小很多，论轻便还是trans更暴力一些

**Comment by Majorry** [comment]
@swjtuer0762 对了大佬 还有一个疑问的点在于原作者在项目中加了slstm和mlstm的比例文件，请问大佬这个库里的xlstm是否默认是1：1的关系呢

**Comment by swjtuer0762** [comment]
我这个项目只是解决了原来作者代码里面的一些bug



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月8日(周五) 上午10:51
收件人: ***@***.***&gt;;
抄送: "Zeng ***@***.******@***.***&gt;;
主题: Re: [swjtuer0762/xLSTMTime] 牛逼作者，不过我有一个问题是Xlstm真的比transformer要好用吗 还是说得观察一段时间 (Issue #2)




 
@swjtuer0762 对了大佬 还有一个疑问的点在于原作者在项目中加了slstm和mlstm的比例文件，请问大佬这个库里的xlstm是否默认是1：1的关系呢

**Comment by swjtuer0762** [comment]
当初很多人运行原作者的代码，遇见非常多的bug，我直接把他们都解决了然后又发了一个上来



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月8日(周五) 上午10:51
收件人: ***@***.***&gt;;
抄送: "Zeng ***@***.******@***.***&gt;;
主题: Re: [swjtuer0762/xLSTMTime] 牛逼作者，不过我有一个问题是Xlstm真的比transformer要好用吗 还是说得观察一段时间 (Issue #2)




 
@swjtuer0762 对了大佬 还有一个疑问的点在于原作者在项目中加了slstm和mlstm的比例文件，请问大佬这个库里的xlstm是否默认是1：1的关系呢

**Comment by Majorry** [comment]
@swjtuer0762 好的 谢谢大佬！！！

**Comment by swjtuer0762** [comment]
这个xlstmtime不是官方的，最好等xlstm官方自己发布有关时序预测的代码



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月8日(周五) 上午10:55
收件人: ***@***.***&gt;;
抄送: "Zeng ***@***.******@***.***&gt;;
主题: Re: [swjtuer0762/xLSTMTime] 牛逼作者，不过我有一个问题是Xlstm真的比transformer要好用吗 还是说得观察一段时间 (Issue #2)




 
@swjtuer0762 好的 谢谢大佬！！！
