### ISSUE TITLE
valid_loss won't drop

### ISSUE THREAD

**Issue by Ryanssssssss** [swjtuer0762/xLSTMTime#3]
Hello，the default dataset perform pretty bad, the valid_loss won't decline while the train_loss keep dropping, and the monitor is valid_loss, how did this happend? is it because of the dataset is not good enough?

**Comment by swjtuer0762** [comment]
I think maybe the xLSTMTime model isn't official.
The dataset is not bad because all current time series forecasts use these datasets to validate their performance, and all metric comparisons are based on the same dataset.

**Comment by Ryanssssssss** [comment]
> I think maybe the xLSTMTime model isn't official. The dataset is not bad because all current time series forecasts use these datasets to validate their performance, and all metric comparisons are based on the same dataset. Message ID: ***@***.***&gt;

Thanks!so maybe is because the model itself has some bug ? so if i want to do the time-series prediction i gotta use the original code?

**Comment by swjtuer0762** [comment]
Yes, so you can wait for the xLSTM official release of the code about the time series forecast. This xLSTMTime is from an unofficial author.

**Comment by Ryanssssssss** [comment]
thanks!
